FROM nvcr.io/nvidia/l4t-base:r32.3.1

RUN apt-get update && \
    apt-get install -y build-essential libboost-python1.62.0 python3-dev python3-pip libpython3-dev python3-numpy python3-cffi && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip3 install --upgrade pip 
RUN pip install --upgrade setuptools 

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]